laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));
Route::get('quemsomos', array('as' => 'quemsomos', 'uses' => 'QuemSomosController@index'));
Route::get('certificacoes', array('as' => 'certificacoes', 'uses' => 'CertificacoesController@index'));
Route::any('representantes/{slug?}', array('as' => 'representantes', 'uses' => 'RepresentantesController@index'));
Route::get('noticias/{slug?}', array('as' => 'noticias', 'uses' => 'NoticiasController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));

Route::post('contato', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));
Route::post('contato', array('as' => 'contato.enviarAlternativo', 'uses' => 'ContatoController@enviaralternativo'));

Route::get('produtos', array('as' => 'produtos', 'uses' => 'ProdutosController@index'));
Route::get('produtos/{slug?}', array('as' => 'produtos.detalhes', 'uses' => 'ProdutosController@detalhes'));
Route::get('sustentabilidade', array('as' => 'sustentabilidade', 'uses' => 'SustentabilidadeController@index'));
Route::get('sustentabilidade/{slug?}', array('as' => 'sustentabilidade.detalhes', 'uses' => 'SustentabilidadeController@detalhes'));
Route::get('areagrafico', array('as' => 'areagrafico', 'uses' => 'AreaGraficoController@index'));
Route::get('areagrafico/{slug?}', array('as' => 'areagrafico.detalhes', 'uses' => 'AreaGraficoController@detalhes'));
Route::get('trabalho', array('as' => 'trabalho', 'uses' => 'TrabalhosController@index'));
Route::post('trabalho', array('as' => 'trabalho.enviar', 'uses' => 'TrabalhosController@enviar'));

// Apresentação de produtos e contato em inglês
Route::get('english', array('as' => 'english.quemsomos', 'uses' => 'EnglishController@quem_somos'));
Route::get('english/certifications', array('as' => 'english.certificacoes', 'uses' => 'EnglishController@certificacoes'));
Route::get('english/contact', array('as' => 'english.contato', 'uses' => 'EnglishController@contato'));
Route::get('english/products', array('as' => 'english.produtos', 'uses' => 'EnglishController@produtos'));
Route::get('english/products/{slug?}', array('as' => 'english.produtos.detalhes', 'uses' => 'EnglishController@produtos_detalhes'));

// Apresentação de produtos e contato em espanhol
Route::get('espanol', array('as' => 'espanol.quemsomos', 'uses' => 'EspanolController@quem_somos'));
Route::get('espanol/certificaciones', array('as' => 'espanol.certificacoes', 'uses' => 'EspanolController@certificacoes'));
Route::get('espanol/contacto', array('as' => 'espanol.contato', 'uses' => 'EspanolController@contato'));
Route::get('espanol/productos', array('as' => 'espanol.produtos', 'uses' => 'EspanolController@produtos'));
Route::get('espanol/productos/{slug?}', array('as' => 'espanol.produtos.detalhes', 'uses' => 'EspanolController@produtos_detalhes'));


Route::get('download/{arquivo?}', function($arquivo){

	$pathToFile = 'assets/files/graficoarquivos/'.$arquivo;

	if(!$arquivo || !file_exists($pathToFile)){
		App::abort('404');
	}else{
		return Response::download($pathToFile);
	}
});

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::get('ajax/pegarCidades/{id}', function($id){
	return Response::json(Cidade::where('estado', '=', $id)->get());
});

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));
Route::post('ajax/adicionarCor', array('before' => 'auth', 'uses' => 'Painel\AjaxController@adicionarCor'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('certificacoes', 'Painel\CertificacoesController');
	Route::resource('representantes', 'Painel\RepresentantesController');
	Route::resource('noticias', 'Painel\NoticiasController');
	Route::resource('quemsomos', 'Painel\QuemSomosController');
	Route::resource('sustentabilidade', 'Painel\SustentabilidadeController');
	Route::resource('produtos', 'Painel\ProdutosController');
	Route::resource('categorias', 'Painel\CategoriasController');
	Route::resource('cores', 'Painel\CoresController');
	Route::resource('produtoscertificacoes', 'Painel\ProdutosCertificacoesController');
	Route::resource('graficoarquivos', 'Painel\GraficoArquivosController');
	Route::resource('graficotextos', 'Painel\GraficoTextosController');
	Route::resource('graficotextositens', 'Painel\GraficoTextosItensController');
	Route::resource('trabalhos', 'Painel\TrabalhosController');
Route::resource('produtosimagens', 'Painel\ProdutosImagensController');
//NOVASROTASDOPAINEL//
});

laravel/app/controllers/painel/GraficoTextosItensController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \File, \GraficoTexto, \GraficoTextoItem;

class GraficoTextosItensController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$texto_id = Input::get('texto_id');

		$texto = GraficoTexto::find($texto_id);

		if(!$texto_id || !$texto) return Redirect::back();

		$this->layout->content = View::make('backend.graficotextositens.index')->with('registros', $texto->itens)
																			   ->with('texto', $texto);
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$texto_id = Input::get('texto_id');

		$texto = GraficoTexto::find($texto_id);

		if(!$texto_id || !$texto) return Redirect::back();

		$this->layout->content = View::make('backend.graficotextositens.form')->with('texto', $texto);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new GraficoTextoItem;

		$object->grafico_textos_id = Input::get('grafico_textos_id');
		$object->titulo = Input::get('titulo');
		$object->descricao = Input::get('descricao');

		try {

			$object->save();

			$object->slug = Str::slug($object->id.' '.$object->titulo);
			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Texto criado com sucesso.');
			return Redirect::route('painel.graficotextositens.index', array('texto_id' => $object->grafico_textos_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Texto!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$item = GraficoTextoItem::find($id);
		$texto = GraficoTexto::find($item->grafico_textos_id);

		if(!$item || !$texto) return Redirect::back();

		$this->layout->content = View::make('backend.graficotextositens.edit')->with('registro', $item)
																			  ->with('texto', $texto);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = GraficoTextoItem::find($id);

		$object->titulo = Input::get('titulo');
		$object->descricao = Input::get('descricao');
		$object->slug = Str::slug($object->id.' '.$object->titulo);
		
		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Texto alterado com sucesso.');
			return Redirect::route('painel.graficotextositens.index', array('texto_id' => $object->grafico_textos_id));

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Texto!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = GraficoTextoItem::find($id);
		$texto_id = $object->grafico_textos_id;
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Texto removido com sucesso.');

		return Redirect::route('painel.graficotextositens.index', array('texto_id' => $texto_id));
	}

}

laravel/app/views/backend/graficotextositens/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	{{$texto->titulo}} - Alterar Conteúdo
        </h2>  

		{{ Form::open( array('route' => array('painel.graficotextositens.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	

				<input type="hidden" name="grafico_textos_id" value="{{$registro->grafico_textos_id}}">

				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" value="{{$registro->titulo}}" required>
				</div>
				<div class="form-group">
					<label for="inputDescrição">Descrição</label>
					<textarea name="descricao" class="form-control" id="inputDescrição" required>{{$registro->descricao }}</textarea>
				</div>

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.graficotextositens.index', array('texto_id' => $texto->id))}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/graficotextositens/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	{{$texto->titulo}} - Adicionar Conteúdo
        </h2>  

		<form action="{{URL::route('painel.graficotextositens.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif
				
				<input type="hidden" name="grafico_textos_id" value="{{$texto->id}}">

				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo'] }}" @endif required>
				</div>
				<div class="form-group">
					<label for="inputDescrição">Descrição</label>
					<textarea name="descricao" class="form-control" id="inputDescrição" required>@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['descricao'] }} @endif</textarea>
				</div>	

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.graficotextositens.index', array('texto_id' => $texto->id))}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/graficotextositens/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        {{$texto->titulo}} - Conteúdo <a href='{{ URL::route('painel.graficotextositens.create', array('texto_id' => $texto->id)) }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Texto</a>
    </h2>
    <hr>
    <a href="{{URL::route('painel.graficotextos.index')}}" title="Voltar" class="btn btn-default">&larr; Voltar para Área do Gráfico - Textos</a>

    <table class='table table-striped table-bordered table-hover'>

        <thead>
            <tr>
                <th>Título</th>
				<th>Descrição</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td>{{ $registro->titulo }}</td>
				<td>{{ Str::words(strip_tags($registro->descricao), 15) }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.graficotextositens.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
						{{ Form::open(array('route' => array('painel.graficotextositens.destroy', $registro->id), 'method' => 'delete')) }}
							<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
						{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>
</div>

@stop