laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home', 'uses' => 'HomeController@index'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));
Route::get('quemsomos', array('as' => 'quemsomos', 'uses' => 'QuemSomosController@index'));
Route::get('certificacoes', array('as' => 'certificacoes', 'uses' => 'CertificacoesController@index'));
Route::any('representantes/{slug?}', array('as' => 'representantes', 'uses' => 'RepresentantesController@index'));
Route::get('noticias/{slug?}', array('as' => 'noticias', 'uses' => 'NoticiasController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));

Route::post('contato', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));
Route::post('contato', array('as' => 'contato.enviarAlternativo', 'uses' => 'ContatoController@enviaralternativo'));

Route::get('produtos', array('as' => 'produtos', 'uses' => 'ProdutosController@index'));
Route::get('produtos/{slug?}', array('as' => 'produtos.detalhes', 'uses' => 'ProdutosController@detalhes'));
Route::get('sustentabilidade', array('as' => 'sustentabilidade', 'uses' => 'SustentabilidadeController@index'));
Route::get('sustentabilidade/{slug?}', array('as' => 'sustentabilidade.detalhes', 'uses' => 'SustentabilidadeController@detalhes'));
Route::get('areagrafico', array('as' => 'areagrafico', 'uses' => 'AreaGraficoController@index'));
Route::get('areagrafico/{slug?}', array('as' => 'areagrafico.detalhes', 'uses' => 'AreaGraficoController@detalhes'));
Route::get('trabalho', array('as' => 'trabalho', 'uses' => 'TrabalhosController@index'));
Route::post('trabalho', array('as' => 'trabalho.enviar', 'uses' => 'TrabalhosController@enviar'));

// Apresentação de produtos e contato em inglês
Route::get('english', array('as' => 'english.quemsomos', 'uses' => 'EnglishController@quem_somos'));
Route::get('english/certifications', array('as' => 'english.certificacoes', 'uses' => 'EnglishController@certificacoes'));
Route::get('english/contact', array('as' => 'english.contato', 'uses' => 'EnglishController@contato'));
Route::get('english/products', array('as' => 'english.produtos', 'uses' => 'EnglishController@produtos'));
Route::get('english/products/{slug?}', array('as' => 'english.produtos.detalhes', 'uses' => 'EnglishController@produtos_detalhes'));

// Apresentação de produtos e contato em espanhol
Route::get('espanol', array('as' => 'espanol.quemsomos', 'uses' => 'EspanolController@quem_somos'));
Route::get('espanol/certificaciones', array('as' => 'espanol.certificacoes', 'uses' => 'EspanolController@certificacoes'));
Route::get('espanol/contacto', array('as' => 'espanol.contato', 'uses' => 'EspanolController@contato'));
Route::get('espanol/productos', array('as' => 'espanol.produtos', 'uses' => 'EspanolController@produtos'));
Route::get('espanol/productos/{slug?}', array('as' => 'espanol.produtos.detalhes', 'uses' => 'EspanolController@produtos_detalhes'));


Route::get('download/{arquivo?}', function($arquivo){

	$pathToFile = 'assets/files/graficoarquivos/'.$arquivo;

	if(!$arquivo || !file_exists($pathToFile)){
		App::abort('404');
	}else{
		return Response::download($pathToFile);
	}
});

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::get('ajax/pegarCidades/{id}', function($id){
	return Response::json(Cidade::where('estado', '=', $id)->get());
});

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));
Route::post('ajax/adicionarCor', array('before' => 'auth', 'uses' => 'Painel\AjaxController@adicionarCor'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banners', 'Painel\BannersController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('certificacoes', 'Painel\CertificacoesController');
	Route::resource('representantes', 'Painel\RepresentantesController');
	Route::resource('noticias', 'Painel\NoticiasController');
	Route::resource('quemsomos', 'Painel\QuemSomosController');
	Route::resource('sustentabilidade', 'Painel\SustentabilidadeController');
	Route::resource('produtos', 'Painel\ProdutosController');
	Route::resource('categorias', 'Painel\CategoriasController');
	Route::resource('cores', 'Painel\CoresController');
	Route::resource('produtoscertificacoes', 'Painel\ProdutosCertificacoesController');
	Route::resource('graficoarquivos', 'Painel\GraficoArquivosController');
	Route::resource('graficotextos', 'Painel\GraficoTextosController');
	Route::resource('graficotextositens', 'Painel\GraficoTextosItensController');
	Route::resource('trabalhos', 'Painel\TrabalhosController');
Route::resource('produtosimagens', 'Painel\ProdutosImagensController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/Produto.php
<?php

class Produto extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'produtos';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function scopeOrdenado($query)
    {
    	return $query->orderBy('ordem', 'ASC')->get();
    }

    public function imagens()
    {
    	return $this->hasMany('ProdutosImagens', 'id_produtos')->orderBy('ordem', 'asc');
    }

    public function categoria()
	{
		return $this->belongsTo('Categoria', 'categorias_id');
	}

	public function cores()
	{
		return $this->belongsToMany('Cor');
	}
	
	public function certificacoes()
	{
		return $this->belongsToMany('ProdutosCertificacoes');
	}

	public function coresArray(){
		$todas = \DB::table('cor_produto')->select('cor_id')->where('produto_id', '=', $this->id)->get();
		
		$r = array();
		foreach ($todas as $key => $value) {
			$r[] = $value->cor_id;
		}
		return $r;
	}

	public function certificacoesArray(){
		$todas = \DB::table('produto_produtos_certificacoes')->select('produtos_certificacoes_id')->where('produto_id', '=', $this->id)->get();
		
		$r = array();
		foreach ($todas as $key => $value) {
			$r[] = $value->produtos_certificacoes_id;
		}
		return $r;
	}
}

laravel/app/controllers/ProdutosController.php
<?php

use \Produto, \Categoria;

class ProdutosController extends BaseController {

	protected $layout = 'frontend.templates.index';

	public function index()
	{
		$this->layout->content = View::make('frontend.produtos.index')->with('categorias', Categoria::ordenado());
	}

	public function detalhes($slug)
	{
		$produto = Produto::where('slug', '=', $slug)->first();

		$outros = Produto::where('categorias_id', '=', $produto->categorias_id)->where('id', '!=', $produto->id)->orderBy('ordem', 'ASC')->get();

		$this->layout->with('css', 'css/produtos');
		$this->layout->content = View::make('frontend.produtos.detalhes')->with('categorias', Categoria::ordenado())
																		 ->with('produto', $produto)
																		 ->with('outros', $outros);
	}
}

laravel/app/controllers/painel/ProdutosController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \File, \Produto, \Categoria, \Cor, \ProdutosCertificacoes;

class ProdutosController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.produtos.index')->with('registros', Produto::ordenado())
																	 ->with('categorias', Categoria::ordenado());
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.produtos.form')->with('categorias', Categoria::ordenado())
																	->with('cores', Cor::ordenado())
																	->with('certificacoes', ProdutosCertificacoes::ordenado());
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Produto;

		$object->categorias_id = Input::get('categorias_id');

		$object->titulo = Input::get('titulo');
		$object->titulo_en = Input::get('titulo_en');
		$object->titulo_es = Input::get('titulo_es');

		$object->tipo = Input::get('tipo');
		$object->tipo_en = Input::get('tipo_en');
		$object->tipo_es = Input::get('tipo_es');

		$object->descricao = Input::get('descricao');
		$object->descricao_en = Input::get('descricao_en');
		$object->descricao_es = Input::get('descricao_es');

		$object->tipo_impressao = Input::get('tipo_impressao');
		$object->tipo_impressao_en = Input::get('tipo_impressao_en');
		$object->tipo_impressao_es = Input::get('tipo_impressao_es');

		$object->aplicacoes = Input::get('aplicacoes');
		$object->aplicacoes_en = Input::get('aplicacoes_en');
		$object->aplicacoes_es = Input::get('aplicacoes_es');

		$object->ph = Input::get('ph');
		$object->ph_en = Input::get('ph_en');
		$object->ph_es = Input::get('ph_es');

		$object->gramatura = Input::get('gramatura');
		$object->gramatura_en = Input::get('gramatura_en');
		$object->gramatura_es = Input::get('gramatura_es');

		$object->folhas = Input::get('folhas');
		$object->folhas_en = Input::get('folhas_en');
		$object->folhas_es = Input::get('folhas_es');

		$object->bobinas = Input::get('bobinas');
		$object->bobinas_en = Input::get('bobinas_en');
		$object->bobinas_es = Input::get('bobinas_es');

		$t=Date('YmdHis');
		$imagem = Thumb::make('imagem', 330, 220, 'produtos/thumbs/', $t);
		Thumb::make('imagem', 900, null, 'produtos/', $t);
		if($imagem) $object->imagem = $imagem;

		try {

			$object->save();


			if(Input::has('cores'))
				$object->cores()->sync(Input::get('cores'));

			if(Input::has('certificacoes'))
				$object->certificacoes()->sync(Input::get('certificacoes'));

			$object->slug = Str::slug($object->id.' '.$object->titulo);
			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Produto criado com sucesso.');
			return Redirect::route('painel.produtos.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::except('imagem'));
			return Redirect::back()->withErrors(array('Erro ao criar Produto!'));

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.produtos.edit')->with('registro', Produto::find($id))
																	->with('categorias', Categoria::ordenado())
																	->with('cores', Cor::ordenado())
																	->with('certificacoes', ProdutosCertificacoes::ordenado());
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Produto::find($id);

		$object->categorias_id = Input::get('categorias_id');

		$object->titulo = Input::get('titulo');
		$object->titulo_en = Input::get('titulo_en');
		$object->titulo_es = Input::get('titulo_es');

		$object->tipo = Input::get('tipo');
		$object->tipo_en = Input::get('tipo_en');
		$object->tipo_es = Input::get('tipo_es');

		$object->descricao = Input::get('descricao');
		$object->descricao_en = Input::get('descricao_en');
		$object->descricao_es = Input::get('descricao_es');

		$object->tipo_impressao = Input::get('tipo_impressao');
		$object->tipo_impressao_en = Input::get('tipo_impressao_en');
		$object->tipo_impressao_es = Input::get('tipo_impressao_es');

		$object->aplicacoes = Input::get('aplicacoes');
		$object->aplicacoes_en = Input::get('aplicacoes_en');
		$object->aplicacoes_es = Input::get('aplicacoes_es');

		$object->ph = Input::get('ph');
		$object->ph_en = Input::get('ph_en');
		$object->ph_es = Input::get('ph_es');

		$object->gramatura = Input::get('gramatura');
		$object->gramatura_en = Input::get('gramatura_en');
		$object->gramatura_es = Input::get('gramatura_es');

		$object->folhas = Input::get('folhas');
		$object->folhas_en = Input::get('folhas_en');
		$object->folhas_es = Input::get('folhas_es');

		$object->bobinas = Input::get('bobinas');
		$object->bobinas_en = Input::get('bobinas_en');
		$object->bobinas_es = Input::get('bobinas_es');

		$object->slug = Str::slug($object->id.' '.$object->titulo);

		$t=Date('YmdHis');
		$imagem = Thumb::make('imagem', 330, 220, 'produtos/thumbs/', $t);
		Thumb::make('imagem', 900, null, 'produtos/', $t);
		if($imagem) $object->imagem = $imagem;

		$cores = Input::has('cores') ? Input::get('cores') : array('0');
		$object->cores()->sync($cores);

		$certs = Input::has('certificacoes') ? Input::get('certificacoes') : array('0');
		$object->certificacoes()->sync($certs);

		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Produto alterado com sucesso.');
			return Redirect::route('painel.produtos.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::except('imagem'));
			return Redirect::back()->withErrors(array('Erro ao alterar Produto! '.$e->getMessage()));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Produto::find($id);
		$object->cores()->sync(array());
		$object->certificacoes()->sync(array());
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Produto removido com sucesso.');

		return Redirect::route('painel.produtos.index');
	}

}

laravel/app/views/backend/produtos/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Produto
        </h2>

		<form action="{{URL::route('painel.produtos.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif

				<div class="form-group">
					<label for="inputCategoria">Categoria</label>
					<select	name="categorias_id" class="form-control" id="inputCategoria" required>
						<option value="">Selecione</option>
						@if(sizeof($categorias) > 0)
							@foreach($categorias as $categoria)
								<option value="{{$categoria->id}}">{{$categoria->titulo}}</option>
							@endforeach
						@endif
					</select>
				</div>

				<div class="form-group">
					<label for="inputTítulo">Título</label>
					<input type="text" class="form-control" id="inputTítulo" name="titulo" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo'] }}" @endif required>
				</div>
				<div class="form-group">
					<label for="inputTítuloEn">Título (inglês)</label>
					<input type="text" class="form-control" id="inputTítuloEn" name="titulo_en" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo_en'] }}" @endif required>
				</div>
				<div class="form-group">
					<label for="inputTítuloEs">Título (espanhol)</label>
					<input type="text" class="form-control" id="inputTítuloEs" name="titulo_es" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['titulo_es'] }}" @endif required>
				</div>

				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem" required>
				</div>

				<div class="form-group">
					<label for="inputTipo">Tipo</label>
					<input type="text" class="form-control" id="inputTipo" name="tipo" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['tipo'] }}" @endif >
				</div>
				<div class="form-group">
					<label for="inputTipoEn">Tipo (inglês)</label>
					<input type="text" class="form-control" id="inputTipoEn" name="tipo_en" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['tipo_en'] }}" @endif >
				</div>
				<div class="form-group">
					<label for="inputTipoEs">Tipo (espanhol)</label>
					<input type="text" class="form-control" id="inputTipoEs" name="tipo_es" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['tipo_es'] }}" @endif >
				</div>

				<div class="form-group">
					<label for="inputDescrição">Descrição</label>
					<textarea name="descricao" class="form-control" id="inputDescrição" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['descricao'] }} @endif</textarea>
				</div>
				<div class="form-group">
					<label for="inputDescriçãoEn">Descrição (inglês)</label>
					<textarea name="descricao_en" class="form-control" id="inputDescriçãoEn" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['descricao_en'] }} @endif</textarea>
				</div>
				<div class="form-group">
					<label for="inputDescriçãoEs">Descrição (espanhol)</label>
					<textarea name="descricao_es" class="form-control" id="inputDescriçãoEs" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['descricao_es'] }} @endif</textarea>
				</div>

				<div class="form-group">
					<label for="inputTipo de Impressão">Tipo de Impressão</label>
					<input type="text" class="form-control" id="inputTipo de Impressão" name="tipo_impressao" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['tipo_impressao'] }}" @endif >
				</div>
				<div class="form-group">
					<label for="inputTipo de ImpressãoEn">Tipo de Impressão (inglês)</label>
					<input type="text" class="form-control" id="inputTipo de ImpressãoEn" name="tipo_impressao_en" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['tipo_impressao_en'] }}" @endif >
				</div>
				<div class="form-group">
					<label for="inputTipo de ImpressãoEs">Tipo de Impressão (espanhol)</label>
					<input type="text" class="form-control" id="inputTipo de ImpressãoEs" name="tipo_impressao_es" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['tipo_impressao_es'] }}" @endif >
				</div>

				<div class="form-group">
					<label for="inputAplicações">Aplicações</label>
					<textarea name="aplicacoes" class="form-control" id="inputAplicações" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['aplicacoes'] }} @endif</textarea>
				</div>
				<div class="form-group">
					<label for="inputAplicaçõesEn">Aplicações (inglês)</label>
					<textarea name="aplicacoes_en" class="form-control" id="inputAplicaçõesEn" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['aplicacoes_en'] }} @endif</textarea>
				</div>
				<div class="form-group">
					<label for="inputAplicaçõesEs">Aplicações (espanhol)</label>
					<textarea name="aplicacoes_es" class="form-control" id="inputAplicaçõesEs" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['aplicacoes_es'] }} @endif</textarea>
				</div>

				<div class="form-group">
					<label for="inputPH">PH</label>
					<input type="text" class="form-control" id="inputPH" name="ph" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['ph'] }}" @endif >
				</div>
				<div class="form-group">
					<label for="inputPHEn">PH (inglês)</label>
					<input type="text" class="form-control" id="inputPHEn" name="ph_en" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['ph_en'] }}" @endif >
				</div>
				<div class="form-group">
					<label for="inputPHEs">PH (espanhol)</label>
					<input type="text" class="form-control" id="inputPHEs" name="ph_es" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['ph_es'] }}" @endif >
				</div>

				<div class="form-group">
					<label for="inputGramatura">Gramatura</label>
					<input type="text" class="form-control" id="inputGramatura" name="gramatura" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['gramatura'] }}" @endif >
				</div>
				<div class="form-group">
					<label for="inputGramaturaEn">Gramatura (inglês)</label>
					<input type="text" class="form-control" id="inputGramaturaEn" name="gramatura_en" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['gramatura_en'] }}" @endif >
				</div>
				<div class="form-group">
					<label for="inputGramaturaEs">Gramatura (espanhol)</label>
					<input type="text" class="form-control" id="inputGramaturaEs" name="gramatura_es" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['gramatura_es'] }}" @endif >
				</div>

				<div class="form-group">
					<label for="inputFolhas">Folhas</label>
					<input type="text" class="form-control" id="inputFolhas" name="folhas" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['folhas'] }}" @endif >
				</div>
				<div class="form-group">
					<label for="inputFolhasEn">Folhas (inglês)</label>
					<input type="text" class="form-control" id="inputFolhasEn" name="folhas_en" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['folhas_en'] }}" @endif >
				</div>
				<div class="form-group">
					<label for="inputFolhasEs">Folhas (espanhol)</label>
					<input type="text" class="form-control" id="inputFolhasEs" name="folhas_es" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['folhas_es'] }}" @endif >
				</div>

				<div class="form-group">
					<label for="inputBobinas">Bobinas</label>
					<textarea name="bobinas" class="form-control" id="inputBobinas" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['bobinas'] }} @endif</textarea>
				</div>
				<div class="form-group">
					<label for="inputBobinasEn">Bobinas (inglês)</label>
					<textarea name="bobinas_en" class="form-control" id="inputBobinasEn" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['bobinas_en'] }} @endif</textarea>
				</div>
				<div class="form-group">
					<label for="inputBobinasEs">Bobinas (espanhol)</label>
					<textarea name="bobinas_es" class="form-control" id="inputBobinasEs" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['bobinas_es'] }} @endif</textarea>
				</div>

				<hr>
				<div class="form-group">
					<label for="inputCertificacoes">Certificações</label><br>
					@if($certificacoes)
						@foreach($certificacoes as $certificacoes)
							<label style="width: 30%;text-align:center;">
								<img src="assets/images/produtoscertificacoes/{{$certificacoes->imagem}}"><br>
								<input type="checkbox" name="certificacoes[]" value="{{$certificacoes->id}}">
								{{$certificacoes->titulo}}
							</label>
						@endforeach
					@endif
				</div>

				<hr>

				<div class="form-group">
					<label for="inputCores">Cores</label><br>
					<div id="contemcores">
						@if($cores)
							@foreach($cores as $cor)
								<label style="width: 30%;"><input type="checkbox"  name="cores[]" value="{{$cor->id}}"> <span style="margin:0; width:10px; height:10px; display:inline-block; border-radius:100%; background:{{$cor->hex}}; border:1px #ccc solid;"></span> {{$cor->titulo}}</label>
							@endforeach
						@endif
					</div>
					<hr>
					<div>
						<a href="#" id="add-cor" class="btn btn-default btn-sm" data-toggle="collapse" data-target="#formcores"><span class="glyphicon glyphicon-plus-sign"></span> Nova cor</a>
						<div style="margin-top:10px;" id="formcores" class="collapse form-inline">
							<input type="text" name="titulo_cor" class="form-control" placeholder="Nome da Cor" id="add-cor-tit">
							<input type="text" name="hex" class="form-control" maxlength="7" placeholder="Código Hexadecimal" id="add-cor-hex">
							<input type="submit" value="Adicionar" class="btn btn-success btn-sm" id="submit-cor">
						</div>
					</div>
				</div>

				<hr>

				<button type="submit" title="Inserir" class="btn btn-success">Inserir Produto</button>

				<a href="{{URL::route('painel.produtos.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>

@stop

laravel/app/views/backend/produtos/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Produtos <a href='{{ URL::route('painel.produtos.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Produto</a>
    </h2>

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='produtos'>

        <thead>
            <tr>
                <th>Ordenar</th>
				<th>Título</th>
				<th>imagens</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
				<td>{{ $registro->titulo }}</td>
				<td>
					<a href="{{URL::route('painel.produtosimagens.index', array('id_produtos' => $registro->id))}}" title="gerenciar imagens" class="btn btn-sm btn-default">gerenciar</a>
				</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.produtos.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
						{{ Form::open(array('route' => array('painel.produtos.destroy', $registro->id), 'method' => 'delete')) }}
							<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
						{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop